version: '3'

services:
  database:
    image: mysql:8.0.33
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-ChangeMe}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-app}
      MYSQL_USER: ${MYSQL_USER:-app}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-ChangeMe}

  app:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:80
    environment:
      APP_ENV: production
      DATABASE_URL: mysql://${MYSQL_USER:-app}:${MYSQL_PASSWORD:-ChangeMe}@database:3306/${MYSQL_DATABASE:-app}

volumes:
  db-data:
